### ISSUE TITLE
Error happens when decomment parse some regular expression

### ISSUE THREAD

**Issue by DIYgod** [vitaly-t/decomment#15]
A minimal demo:
```js
var decomment = require('decomment');
var code = 'if(true){}/\\d/.test(\'\')';
decomment(code);
```

Error log:
```
Error: Line 1: Unexpected token ILLEGAL
    at ErrorHandler.constructError (/Users/DIYgod/Code/test/node_modules/esprima/dist/esprima.js:5004:22)
    at ErrorHandler.createError (/Users/DIYgod/Code/test/node_modules/esprima/dist/esprima.js:5020:27)
    at ErrorHandler.throwError (/Users/DIYgod/Code/test/node_modules/esprima/dist/esprima.js:5027:21)
    at Scanner.throwUnexpectedToken (/Users/DIYgod/Code/test/node_modules/esprima/dist/esprima.js:5155:35)
    at Scanner.getComplexIdentifier (/Users/DIYgod/Code/test/node_modules/esprima/dist/esprima.js:5488:23)
    at Scanner.scanIdentifier (/Users/DIYgod/Code/test/node_modules/esprima/dist/esprima.js:5556:67)
    at Scanner.lex (/Users/DIYgod/Code/test/node_modules/esprima/dist/esprima.js:6223:26)
    at Tokenizer.getNextToken (/Users/DIYgod/Code/test/node_modules/esprima/dist/esprima.js:6666:84)
    at Object.tokenize (/Users/DIYgod/Code/test/node_modules/esprima/dist/esprima.js:154:36)
    at Object.parseRegEx (/Users/DIYgod/Code/test/node_modules/decomment/lib/utils.js:37:13)
```

**Comment by vitaly-t** [comment]
When Esprima doesn’t like your code, it must an invalid JavaScript ;)

**Comment by DIYgod** [comment]
The compressed source code is like
```js
if(true){}/\d/.test('');
```

Then [gulp-strip-comments](https://github.com/RnbWd/gulp-strip-comments) parses my code with `toString` function to a string like `'if(true){}/\\d/.test(\'\')'`

Should I make an issue to gulp-strip-comments?

**Comment by vitaly-t** [comment]
I’m not sure, I will test it later though ;)

**Comment by vitaly-t** [comment]
Here's the test I've done, and it all looks fine:

```js
const decomment = require('decomment');

const str = 'if(true){}/\d/.test(\'\');';

const s = decomment(str);

console.log(s);
//=> if(true){}/d/.test('');
```

**Comment by DIYgod** [comment]
Sorry for my late reply.

The error happends in `/\\d/`, not `/\d/`

**Comment by vitaly-t** [comment]
You should log/chase it against the [Esprima] engine as the one that fails to process that piece of JavaScript.

There is nothing that can be done about it within this library.

[Esprima]:https://github.com/jquery/esprima

**Comment by vitaly-t** [comment]
There, I've opened an issue: [Fails on a compressed piece of code](https://github.com/jquery/esprima/issues/1873).

**Comment by DIYgod** [comment]
Thanks!

**Comment by vitaly-t** [comment]
The author of Esprima claims he fixed it, but I've just released an update, and I can still reproduce the issue :(

**Comment by vitaly-t** [comment]
Esprima hasn't been published for 3 years, and now looks a bit abandoned.

I presently do not have time for rewriting this library to use a different parser.
