### ISSUE TITLE
Cannot process js containing jsx code

### ISSUE THREAD

**Issue by wll8** [vitaly-t/decomment#22]
# Cannot process js containing jsx code

- If it is a pure jsx file, does this tool support jsx?
- Jsx is mixed in js, which comes from `*.vue` file

## environment
- decomment@0.9.4

## Source code
Js file containing jsx

``` js
// @ is an alias to /src
import { api } from '@/http/api'

import exSlot from '@/components/exSlot.vue'
import download from 'downloadjs'

export default {
  components: {
    exSlot,
  },
  data() {
    let start = new Date(Date.now() - 1000 * 60 * 60 * 24 * 7)
    let end = new Date()
  },
  watch: {},
  methods: {
    tableColGet(list = []) {
      return [
        {
          label: `duration`,
          width: 70,
          key: `duration`,
          render(h, { col, scope }) {
            return <span>{`${scope.row.duration}s`}</span>
          },
        },
        ...list,
        {
          label: `audio`,
          width: 50,
          key: `audioPath`,
          render(h, { col, scope }) {
            return scope.row.audioPath ? (
              <el-button
                type="text"
                vOn:click={() => {
                  console.log(`col, scope`, col, scope)
                  // download(scope.row.audioPath)
                  window.open(scope.row.audioPath)
                }}
              >
                {
                  // <i class="el-icon-download"></i>
                }
                download
              </el-button>
            ) : (
              <span>--</span>
            )
          },
        },
      ]
    },
  },
}
```

## How to use
``` js
outStr = decomment(str, {
  trim: true,
});
```

## Get error
This looks similar to [issues/1](https://github.com/vitaly-t/decomment/issues/1#issuecomment-168159288)

``` txt
error Error: Line 24: Invalid regular expression: missing /
    at ErrorHandler.constructError (D:\git2\remove-comments\node_modules\_esprima@4.0.1@esprima\dist\esprima.js:5012:22)
    at ErrorHandler.createError (D:\git2\remove-comments\node_modules\_esprima@4.0.1@esprima\dist\esprima.js:5028:27)
    at ErrorHandler.throwError (D:\git2\remove-comments\node_modules\_esprima@4.0.1@esprima\dist\esprima.js:5035:21)
    at Scanner.throwUnexpectedToken (D:\git2\remove-comments\node_modules\_esprima@4.0.1@esprima\dist\esprima.js:5164:35)
    at Scanner.scanRegExpBody (D:\git2\remove-comments\node_modules\_esprima@4.0.1@esprima\dist\esprima.js:6139:23)
    at Scanner.scanRegExp (D:\git2\remove-comments\node_modules\_esprima@4.0.1@esprima\dist\esprima.js:6204:29)
    at Tokenizer.getNextToken (D:\git2\remove-comments\node_modules\_esprima@4.0.1@esprima\dist\esprima.js:6675:56)
    at Object.tokenize (D:\git2\remove-comments\node_modules\_esprima@4.0.1@esprima\dist\esprima.js:154:36)
    at Object.parseRegEx (D:\git2\remove-comments\node_modules\_decomment@0.9.4@decomment\lib\utils.js:37:13)
    at parser (D:\git2\remove-comments\node_modules\_decomment@0.9.4@decomment\lib\parser.js:36:27) {
  index: 570,
  lineNumber: 24,
  description: 'Invalid regular expression: missing /'
}
```

**Comment by vitaly-t** [comment]
JSX isn't JavaScript, and can only be processed as text - see [decomment.text](https://github.com/vitaly-t/decomment#decommenttexttext-options--string).
